### PR TITLE
Enhancements and windows-specific updates

### PR DESCRIPTION
**Pull request by oldium**
* [Windows] Fixed decoding of Chromium-based cookies on Windows
* Allow reading of correct Firefox 67+ default profile cookies
* Added Edge and Edge Dev profiles

For consideration, I am using it like that. Feel free to use it, modify it, drop it 😊

### CODE REVIEW

**Comment by oldium** [comment]
I am thinking about removing the opened-file copying via VSS and replacing it by a file copy hook instead - this way the passed-in object could easily cache the VSS instance to copy from multiple locations at once. Moreover, the `shadowcopy` library dependency would be removed from browsercookie. I will do it during this or next week, it depends on time.

**Comment by oldium** [comment]
Done 😊

**Comment by oldium** [comment]
I removed the helper; I will have a different solution for that.

**Comment by richardpenman** [comment]
awesome, thanks very much for the PR!

**Comment by carlitorendon** [comment]
One more question @richardpenman do we need to bump the version in setup.py? 

If the answer is yes, you ok if I bump it to 0.8.0?

**Pull request merged**
